services:
  mongodb:
    image: mongo:7
    container_name: gdash-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: gdash
    volumes:
      - mongodb_data:/data/db
    networks:
      - gdash-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: gdash-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gdash-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gdash-backend
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/gdash?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3000
      DEFAULT_USER_EMAIL: admin@example.com
      DEFAULT_USER_PASSWORD: 123456
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - gdash-network

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    container_name: gdash-python
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin123
      RABBITMQ_QUEUE: weather_data
      WEATHER_API_URL: https://api.open-meteo.com/v1/forecast
      LATITUDE: -22.7922408
      LONGITUDE: -45.2036523
      COLLECTION_INTERVAL: 60
    depends_on:
      - rabbitmq
    volumes:
      - ./python-service:/app
    networks:
      - gdash-network

  go-worker:
    build:
      context: ./go-worker
      dockerfile: Dockerfile
    container_name: gdash-go-worker
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin123
      RABBITMQ_QUEUE: weather_data
      API_URL: http://backend:3000/api/weather/logs
    depends_on:
      - rabbitmq
      - backend
    networks:
      - gdash-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gdash-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - gdash-network

volumes:
  mongodb_data:
  rabbitmq_data:

networks:
  gdash-network:
    driver: bridge
